[project]
name = "ml-ss26-assignments"
version = "0.1.0"
description = "python project for the SS26 machine learning course @ KIT"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "click>=8.4.2",
    "de-core-news-sm",
    "en-core-web-sm",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "matplotlib==3.10.0",
        "scikit-learn>=1.9.0",
    "scipy>=1.17.1",
    "numpy==1.26.4",
    "spacy==3.8.13",
    "torch==2.8.0",
]

[tool.uv.sources]
de-core-news-sm = { url = "https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.8.0/de_core_news_sm-3.8.0.tar.gz" }
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0.tar.gz" }

# To switch backends: uncomment the desired block below, run `uv sync`.
# --- OPTION 1: CUDA 12.8 ---
torch = { index = "pytorch-cu128" }

# --- OPTION 2: CPU ONLY ---
# torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
